server:
  port: "${PORT:8080}"
  servlet:
    context-path: /cuu-tro

spring:
  application:
    name:identify-service
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"
    username: "${MYSQL_USER}"
    password: "${MYSQL_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    hibernate:
      ddl-auto: update
    show-sql: true
