server:
  port: 8080
  servlet:
    context-path: /cuu-tro

spring:
  application:
    name:identify-service
  datasource:
    url: "jdbc:mysql://localhost:3306/cuu_tro"
    username: root
    password: 123456
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    hibernate:
      ddl-auto: update
    show-sql: true
